apiVersion: apps/v1
kind: Deployment
metadata:
  name: complete-production-e2e-deployment
spec:
  selector:
    matchLabels:
      app: complete-production-e2e-app
  template:
    metadata:
      labels:
        app: complete-production-e2e-app
    spec:
      containers:
        - name: complete-production-e2e-app
          image: 21701jake/complete-production-e2e-pipeline:1.0.0-45
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 9090